-- 1. 사용자(스키마) 접속 상태이므로 DATABASE 생성/USE 대신 계정 개념을 사용합니다.
-- (이미 접속한 계정에서 아래 테이블들을 생성하면 됩니다.)

-- 2. 주소록 테이블 (t_address_book)
DROP TABLE IF EXISTS t_address_book; -- 오라클 23ai부터 IF EXISTS 지원
CREATE TABLE t_address_book (
    c_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- AUTO_INCREMENT 대체
    c_name       VARCHAR2(50) NOT NULL,                               -- VARCHAR -> VARCHAR2
    c_age        NUMBER NOT NULL,                                     -- INT -> NUMBER
    c_phone      VARCHAR2(20),
    c_address    VARCHAR2(100),
    c_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. 샘플 데이터 삽입
-- 오라클은 한 번에 여러 행을 넣는 형식이 MySQL과 다르므로 개별 INSERT로 실행합니다.
INSERT INTO t_address_book (c_name, c_age, c_phone, c_address) VALUES ('김철수', 32, '010-1234-5678', '서울특별시 강남구 역삼동');
INSERT INTO t_address_book (c_name, c_age, c_phone, c_address) VALUES ('이영희', 28, '010-2345-6789', '부산광역시 해운대구 우동');
INSERT INTO t_address_book (c_name, c_age, c_phone, c_address) VALUES ('박민수', 45, '010-3456-7890', '대구광역시 수성구 범어동');
INSERT INTO t_address_book (c_name, c_age, c_phone, c_address) VALUES ('최지현', 37, '010-4567-8901', '인천광역시 남동구 구월동');
INSERT INTO t_address_book (c_name, c_age, c_phone, c_address) VALUES ('정우성', 29, '010-5678-9012', '광주광역시 서구 치평동');
INSERT INTO t_address_book (c_name, c_age, c_phone, c_address) VALUES ('한지민', 41, '010-6789-0123', '대전광역시 유성구 봉명동');
INSERT INTO t_address_book (c_name, c_age, c_phone, c_address) VALUES ('오세훈', 35, '010-7890-1234', '울산광역시 남구 삼산동');
INSERT INTO t_address_book (c_name, c_age, c_phone, c_address) VALUES ('윤아름', 26, '010-8901-2345', '경기도 성남시 분당구 정자동');
INSERT INTO t_address_book (c_name, c_age, c_phone, c_address) VALUES ('강호동', 50, '010-9012-3456', '경상남도 창원시 의창구 팔용동');
INSERT INTO t_address_book (c_name, c_age, c_phone, c_address) VALUES ('배수지', 31, '010-0123-4567', '강원특별자치도 원주시 무실동');

-- 4. 사용자 테이블 (t_user)
DROP TABLE IF EXISTS t_user;
CREATE TABLE t_user (
    c_id   VARCHAR2(50) PRIMARY KEY,
    c_pass VARCHAR2(255) NOT NULL,
    c_role VARCHAR2(255)
);

INSERT INTO t_user (c_id, c_pass, c_role)
VALUES (
    'admin',
    'Bs0RhQ8X3l72YJuIQeZpXA==:Zbw4+TU7JShKOWq14s1sZgEIVm7U7zy4DhQVTj75kA4=',
    'admin, manager'
);

-- 5. 변경사항 반영
COMMIT;